enum Actions {

    // theme
    THEME_TOGGLE = 'THEME_TOGGLE',

    SET_CURRENT_DATE = 'SET_CURRENT_DATE',

    // data (filters)
    SET_TIMESPAN_FOR_GRAPHS = 'SET_TIMESPAN_FOR_GRAPHS',
    SET_START_DATE_FOR_GRAPHS = 'SET_START_DATE_FOR_GRAPHS',

    // data (async)
    FETCH_DATA_START = 'FETCH_DATA_START',
    FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILED = 'FETCH_DATA_FAILED'
}

export default Actions;
