enum Actions {

    // theme
    THEME_TOGGLE = 'THEME_TOGGLE',

    // data
    SET_TIMESPAN_FOR_GRAPHS = 'SET_TIMESPAN_FOR_GRAPHS',
    FETCH_TEMPERATURE_START = 'FETCH_TEMPERATURE_START',
    FETCH_TEMPERATURE_SUCCESS = 'FETCH_TEMPERATURE_SUCCESS',
    FETCH_TEMPERATURE_FAILED = 'FETCH_TEMPERATURE_FAILED'
}

export default Actions;
